//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.25 at 10:37:16 PM EDT 
//


package gov.nist.example.models.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.example.models.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AEm_QNAME = new QName("http://csrc.nist.gov/ns/oscal/1.0", "em");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.example.models.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link gov.nist.example.models.types.Em }
     * 
     */
    public gov.nist.example.models.types.Em createEm() {
        return new gov.nist.example.models.types.Em();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Strong }
     * 
     */
    public Strong createStrong() {
        return new Strong();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Img }
     * 
     */
    public Img createImg() {
        return new Img();
    }

    /**
     * Create an instance of {@link A.Em }
     * 
     */
    public A.Em createAEm() {
        return new A.Em();
    }

    /**
     * Create an instance of {@link Insert }
     * 
     */
    public Insert createInsert() {
        return new Insert();
    }

    /**
     * Create an instance of {@link LastModifiedDate }
     * 
     */
    public LastModifiedDate createLastModifiedDate() {
        return new LastModifiedDate();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link OscalVersion }
     * 
     */
    public OscalVersion createOscalVersion() {
        return new OscalVersion();
    }

    /**
     * Create an instance of {@link DocId }
     * 
     */
    public DocId createDocId() {
        return new DocId();
    }

    /**
     * Create an instance of {@link Prop }
     * 
     */
    public Prop createProp() {
        return new Prop();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link ShortName }
     * 
     */
    public ShortName createShortName() {
        return new ShortName();
    }

    /**
     * Create an instance of {@link Desc }
     * 
     */
    public Desc createDesc() {
        return new Desc();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link OrgName }
     * 
     */
    public OrgName createOrgName() {
        return new OrgName();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link OrgId }
     * 
     */
    public OrgId createOrgId() {
        return new OrgId();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddrLine }
     * 
     */
    public AddrLine createAddrLine() {
        return new AddrLine();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link PostalCode }
     * 
     */
    public PostalCode createPostalCode() {
        return new PostalCode();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link H1 }
     * 
     */
    public H1 createH1() {
        return new H1();
    }

    /**
     * Create an instance of {@link H2 }
     * 
     */
    public H2 createH2() {
        return new H2();
    }

    /**
     * Create an instance of {@link H3 }
     * 
     */
    public H3 createH3() {
        return new H3();
    }

    /**
     * Create an instance of {@link H4 }
     * 
     */
    public H4 createH4() {
        return new H4();
    }

    /**
     * Create an instance of {@link H5 }
     * 
     */
    public H5 createH5() {
        return new H5();
    }

    /**
     * Create an instance of {@link H6 }
     * 
     */
    public H6 createH6() {
        return new H6();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link Ol }
     * 
     */
    public Ol createOl() {
        return new Ol();
    }

    /**
     * Create an instance of {@link Pre }
     * 
     */
    public Pre createPre() {
        return new Pre();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Th }
     * 
     */
    public Th createTh() {
        return new Th();
    }

    /**
     * Create an instance of {@link Org }
     * 
     */
    public Org createOrg() {
        return new Org();
    }

    /**
     * Create an instance of {@link Select }
     * 
     */
    public Select createSelect() {
        return new Select();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link Catalog }
     * 
     */
    public Catalog createCatalog() {
        return new Catalog();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Usage }
     * 
     */
    public Usage createUsage() {
        return new Usage();
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link Guideline }
     * 
     */
    public Guideline createGuideline() {
        return new Guideline();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link Subcontrol }
     * 
     */
    public Subcontrol createSubcontrol() {
        return new Subcontrol();
    }

    /**
     * Create an instance of {@link BackMatter }
     * 
     */
    public BackMatter createBackMatter() {
        return new BackMatter();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Rlink }
     * 
     */
    public Rlink createRlink() {
        return new Rlink();
    }

    /**
     * Create an instance of {@link Hash }
     * 
     */
    public Hash createHash() {
        return new Hash();
    }

    /**
     * Create an instance of {@link Base64 }
     * 
     */
    public Base64 createBase64() {
        return new Base64();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link A.Em }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://csrc.nist.gov/ns/oscal/1.0", name = "em", scope = A.class)
    public JAXBElement<A.Em> createAEm(A.Em value) {
        return new JAXBElement<A.Em>(_AEm_QNAME, A.Em.class, A.class, value);
    }

}
